.PHONY: clean All

All:
	@echo "----------Building project:[ first_program - Debug ]----------"
	@cd "first_program" && "$(MAKE)" -f  "first_program.mk"
clean:
	@echo "----------Cleaning project:[ first_program - Debug ]----------"
	@cd "first_program" && "$(MAKE)" -f  "first_program.mk" clean
